source 'https://rubygems.org'
ruby '2.5.0'
gem 'telegram-bot-ruby'
gem 'dotenv'
gem 'sequel'
gem 'pg'
gem 'rufus-scheduler'
gem 'sucker_punch', '~> 2.0'
gem 'oj'
gem 'rest-client'

gem 'awesome_print'
